// Source code is unavailable, and was generated by the Fernflower decompiler.
package com.cloud.sdk.util;

import java.util.Locale;

public class BinaryUtils {
    public static String toHex(byte[] data) {
        StringBuffer sbuff = new StringBuffer(data.length * 2);
        byte[] var2 = data;
        int var3 = data.length;

        for(int var4 = 0; var4 < var3; ++var4) {
            byte bye = var2[var4];
            String hexStr = Integer.toHexString(bye);
            if (hexStr.length() == 1) {
                sbuff.append("0");
            } else if (hexStr.length() == 8) {
                hexStr = hexStr.substring(6);
            }

            sbuff.append(hexStr);
        }

        return sbuff.toString().toLowerCase(Locale.getDefault());
    }
}
